### PR TITLE
Added support for .svg and .svgz file formats

### PR DESCRIPTION
**Pull request by jirka-h**

### CODE REVIEW

**Comment by jirka-h** [comment]
I have added support for .svgz files. 

It resolves https://github.com/gfwilliams/ThinGallery/issues/21

BTW, I have the following in /etc/httpd/conf/httpd.conf  configuration to support .svgz file format:

```
   AddType image/svg+xml .svg .svgz
   AddEncoding gzip .svgz
```

**Comment by gfwilliams** [comment]
Thanks! Actually looking again at this I think `getImageThumbnail` should probably only be trying to get the thumbnail from JPEG files (non just non-SVGZ) - for all the other files it's kind of just wasting effort trying to load the first 60k, it should just skip that and go straight to putting the original image URL in as the thumbnail.

I don't know if you want to look at changing that or if I should?

**Comment by jirka-h** [comment]
Yes, I fully agree! I see warnings like this in the console (here for the png file):
`thread_log.numa.hist.png is not a valid JPEG`

I'm unfamiliar with the source code, so I would prefer it if you could do this. 

Thank you! 

BTW, I really appreciate that you have shared this project. It makes my life much easier.

**Comment by jirka-h** [comment]
Thank you, Gordon! 

I have tested it and it works nicely both with .svg and .svgz files. 

Just one remark - `</div>` on line 541 is unnecessary - there is no opening `<div>` element matching it. 
https://github.com/gfwilliams/ThinGallery/blob/master/gallery.html#L541

See also https://github.com/gfwilliams/ThinGallery/pull/23

Jirka

**Pull request closed without merging**
